# Generated by Django 6.0.5 on 2026-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Carrinho'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_uso',
            field=models.DateField(verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(max_length=20, verbose_name='Período'),
        ),
    ]
