# Generated by Django 6.0.5 on 2026-05-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_equipamento_nome_alter_reserva_data_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.CharField(default='', max_length=50, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(max_length=20, verbose_name='Período/Horário'),
        ),
    ]
