# Generated by Django 6.0.5 on 2026-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_equipamento_disponivel_reserva_sala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
