# Generated by Django 6.0.5 on 2026-05-27 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_equipamento_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='periodo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario_fim',
            field=models.TimeField(default=datetime.time(23, 59)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
